export CLICOLOR=YES

if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi

source ~/.bash_aliases

# export PATH="/usr/local/opt/libxml2/bin:$PATH"
alias dev='ssh -p620 -A kjm@dev.administratehq.com'
